# Generated by Django 2.1.5 on 2023-03-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
